version: 2
updates:
  - package-ecosystem: npm
    schedule:
      interval: weekly
    directory: /
    rebase-strategy: auto
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
    directory: /
    rebase-strategy: auto
