name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
          - 18
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install deps normally
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: pnpm i

      - name: Run unit tests
        run: pnpm run test:unit
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
          - 18
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install deps normally
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: pnpm i

      - name: Run e2e tests
        run: pnpm run test:e2e
